[package]
name = "shush"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/Pogodaanton/shush"
license = "MIT"

[dependencies]
directories = "6.0.0"
env_logger = "0.11.8"
iced = { version = "0.13.1", features = ["tokio"]}
librespot = "0.7.1"
log = "0.4.28"
serde = "1.0.228"
tokio = { version = "1.47.1" , features = ["fs"]}
tokio-stream = "0.1.17"
toml = { version = "0.9.7" , features = ["parse", "serde"]}
